export const AUDIT_ACTIONS = {
  CREATE_COOPERATIVE: "CREATE_COOPERATIVE",
  CREATE_COOP_ADMIN: "CREATE_COOP_ADMIN",

  REGISTER_FARMER: "REGISTER_FARMER",

  CREATE_LOAN: "CREATE_LOAN",
  APPROVE_LOAN: "APPROVE_LOAN",
  REJECT_LOAN: "REJECT_LOAN",

  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};
